# (PART\*) Charger et manipuler des données {-}

# Objectifs d'apprentissage

**Résumé :** Dans cet atelier, vous apprendrez comment charger et
visualiser des données dans R. Vous apprendrez certaines fonctions
permettant d'examiner vos données et vous apprendrez comment corriger
certaines erreurs communes se produisant lors du chargement des données.
Finalement, vous verrez l'importance de sauvegarder votre travail dans
un script R, soit un fichier texte contenant tous vos codes et
permettant de refaire toutes vos analyses en appuyant sur une seule
touche (ou deux, ou trois peut-être...). Ensuite, nous présenterons
tidyr et dplyr pour vous aider à transformer et à gérer le format de vos
données ainsi que pour appliquer des fonctions simples ou complexes sur
des sous-groupes de vos jeux de données. Cet atelier s'avérera utile non
seulement pour les participants suivant notre série d'ateliers, mais
également pour ceux et celles d'entre vous connaissant déjà le langage R
et cherchant à maîtriser des outils plus avancés pour l'analyse et la
visualisation de vos données.

1.  Créer un projet RStudio
2.  Écrire un script dans R
3.  Charger, explorer et enregister des données
4.  Manipuler des jeux de données avec tidyr, dplyr, maggritr

# Préparez-vous pour cet atelier

Tout le matériel de l'atelier se trouve sur [github.com/QCBSRworkshops/workshop02](https://github.com/QCBSRworkshops/workshop02). Cela inclut un [script R](https://r.qcbs.ca/workshop02/book-fr/workshop02-script-fr.R) qui rassemble tous les morceaux de code présentés dans ce livre.

Pour cet atelier, nous travaillerons avec les jeux de données suivants :

* Jeux de données CO2, airquality et ChickWeight

> Pour télécharger ces données, faites un clic droit + enregistrer sur la page qui s'ouvre.

Vous devriez également vous assurer que vous avez téléchargé, installé et chargé les librairies R suivantes:

* [dplyr](https://cran.r-project.org/package=dplyr)
* [tidyr](https://cran.r-project.org/package=tidyr)
* [magrittr](https://cran.r-project.org/package=magrittr)
